created all sections on right side
Task-Book/Frontend pull request #9
Opened 2023-01-25 17:38 UTC by yana-norinskaya

2023-01-26 19:11 UTC, venmovs requested changes

2023-01-26 19:11 UTC, venmovs commented on src/components/Sections/Observation/index.tsx
> +        Больше всего задач вы создаете в Понедельник
давай уберем хардкод и поставим пропс, так как это данные тебе будут приходить с сервера

2023-01-26 19:11 UTC, venmovs commented on src/components/Sections/Time/index.tsx
> +const paddingBottom = "10px";
от этого желательно избавиться и придумать более изящное решение

2023-01-26 19:11 UTC, venmovs commented on src/components/Sections/Successes/index.tsx
> +        {date.map((infoTask) => (
старайся все делать консистентно, у тебя где-то вынесен map где-то внутри jsx

2023-01-26 19:11 UTC, venmovs commented on src/components/Sections/Time/index.tsx
> +            <Calendar /> <TimeText>12:33:40</TimeText>
Сделай подсчет времени через js, избавься от хардкода

2023-01-26 19:11 UTC, venmovs commented on src/components/Sections/Time/index.tsx
> +            <Clock /> <TimeText>5 апреля 2021</TimeText>
Дату тоже можно сделать через js

2023-01-27 09:56 UTC, yana-norinskaya commented on src/components/Sections/Observation/index.tsx
> +        Больше всего задач вы создаете в Понедельник
добавила фэйковые данные в эту папку пока)

2023-01-27 09:57 UTC, yana-norinskaya commented on src/components/Sections/Time/index.tsx
> +const paddingBottom = "10px";
сделала с помощью theme)

2023-01-27 09:57 UTC, yana-norinskaya commented on src/components/Sections/Successes/index.tsx
> +        {date.map((infoTask) => (
вынесла все map, которые есть)

2023-01-27 09:57 UTC, yana-norinskaya commented on src/components/Sections/Time/index.tsx
> +            <Calendar /> <TimeText>12:33:40</TimeText>
сделала)

2023-01-27 09:57 UTC, yana-norinskaya commented on src/components/Sections/Time/index.tsx
> +            <Clock /> <TimeText>5 апреля 2021</TimeText>
сделала)

2023-01-28 20:16 UTC, venmovs approved these changes

2023-01-28 20:16 UTC, venmovs commented on src/components/Logout/index.tsx
> +import logOut from "../../assets/log-in.svg";
может у меня лагает, но тут опять logOut

2023-01-28 20:16 UTC, venmovs commented on src/components/Sections/Fact/index.tsx
> +      Человек, который просыпается в 6 утра, по статистике, закрывает все задачи
это тоже должно все прийти с бэка, стоит сделать заготовку под это

2023-01-28 20:16 UTC, venmovs commented on src/components/Sections/Observation/fakeData.ts
> +export const outputByTasks = [
может стоит назвать не fakeData а просто mock

2023-01-28 20:16 UTC, venmovs commented on src/components/Sections/Time/useSetDate.ts
> +  return { date };
может просто вернуть date?

2023-01-29 09:34 UTC, merged